async page => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.setViewportSize({ width: 1600, height: 1000 });
  const root = page.locator('.app-shell:visible');
  await root.locator('input[type=file]').setInputFiles('public/example.aov.json');
  await page.getByRole('button', { name: '匯入專案', exact: true }).click();
  if (await page.getByRole('button', { name: '切換正向線模式', exact: true }).count()) await page.getByRole('button', { name: '切換正向線模式', exact: true }).click();
  await page.getByRole('button', { name: '新增一般節點', exact: true }).click();
  await page.getByRole('textbox', { name: '節點名稱', exact: true }).fill('返回處理');
  await page.getByRole('button', { name: '關閉設定面板', exact: true }).click();
  await page.getByRole('button', { name: '顯示完整畫布', exact: true }).click();
  const source = root.locator('.node-card').filter({ has: page.locator('strong', { hasText: '驗證訂單' }) });
  const middle = root.locator('.node-card').filter({ has: page.locator('strong', { hasText: '返回處理' }) });
  const target = root.locator('.node-card').filter({ has: page.locator('strong', { hasText: '接收訂單' }) });
  const forward = root.locator('.react-flow__edge-default .react-flow__edge-path');
  const original = await forward.first().getAttribute('d');
  if (await root.locator('.node-card').filter({ hasText: /前一步|下一步/ }).count()) throw new Error('節點卡片仍顯示前一步／下一步');
  await page.getByRole('button', { name: '切換返回線模式', exact: true }).click();
  const from = source.locator('.return-bottom'); const middleIn = middle.locator('.return-right'); const middleOut = middle.locator('.return-left'); const to = target.locator('.return-bottom');
  if (await source.locator('.return-bottom').count() !== 1 || await middle.locator('.return-bottom').count() !== 1 || await target.locator('.return-bottom').count() !== 1) throw new Error('每個節點應只有一個下方返回接點');
  if (await middleIn.count() !== 1 || await middleOut.count() !== 1) throw new Error('中間節點缺少右側返回入口或左側返回出口');
  const sourceBox = await source.boundingBox(), fromBox = await from.boundingBox(), targetBox = await target.boundingBox(), toBox = await to.boundingBox();
  if (Math.abs(fromBox.y + fromBox.height / 2 - sourceBox.y - sourceBox.height) > 15 || Math.abs(toBox.y + toBox.height / 2 - targetBox.y - targetBox.height) > 15) throw new Error('返回接點不在節點下方');
  const count = await root.locator('.react-flow__edge-return').count();
  const reverseA = await to.boundingBox(), reverseB = await from.boundingBox();
  await page.mouse.move(reverseA.x + reverseA.width / 2, reverseA.y + reverseA.height / 2); await page.mouse.down();
  await page.mouse.move(reverseB.x + reverseB.width / 2, reverseB.y + reverseB.height / 2, { steps: 15 }); await page.mouse.up();
  if (await root.locator('.react-flow__edge-return').count() !== count) throw new Error('未阻擋由左向右的返回線');
  if (!(await root.getByRole('status').innerText()).includes('右方節點連回左方節點')) throw new Error('未說明返回方向限制');
  const a = await from.boundingBox(), b = await middleIn.boundingBox();
  await page.mouse.move(a.x + a.width / 2, a.y + a.height / 2); await page.mouse.down();
  await page.mouse.move(b.x + b.width / 2, b.y + b.height / 2, { steps: 15 }); await page.mouse.up();
  await page.getByRole('heading', { name: '返回與 Loop', exact: true }).waitFor();
  await page.waitForFunction(expected => document.querySelectorAll('.app-shell:not([hidden]) .react-flow__edge-return').length === expected, count + 1);
  if (await root.locator('.react-flow__edge-return').count() !== count + 1) throw new Error('返回拖線失敗');
  await page.getByRole('button', { name: '關閉設定面板', exact: true }).click();
  const c = await middleOut.boundingBox(), d = await to.boundingBox();
  await page.mouse.move(c.x + c.width / 2, c.y + c.height / 2); await page.mouse.down();
  await page.mouse.move(d.x + d.width / 2, d.y + d.height / 2, { steps: 15 }); await page.mouse.up();
  await page.getByRole('heading', { name: '返回與 Loop', exact: true }).waitFor();
  await page.waitForFunction(expected => document.querySelectorAll('.app-shell:not([hidden]) .react-flow__edge-return').length === expected, count + 2);
  if (await root.locator('.react-flow__edge-return').count() !== count + 2) throw new Error('中間節點返回輸出連接失敗');
  const paths = root.locator('.react-flow__edge-return .react-flow__edge-path'); const intoMiddle = paths.nth(count); const outOfMiddle = paths.nth(count + 1);
  if (await intoMiddle.evaluate(el => getComputedStyle(el).strokeDasharray) === 'none') throw new Error('返回線不是虛線');
  if (!/V.*H/.test(await intoMiddle.getAttribute('d'))) throw new Error('返回線未由來源底部進入中間節點右側');
  if (!/H.*V/.test(await outOfMiddle.getAttribute('d'))) throw new Error('返回線未由中間節點左側接入目標底部');
  await page.getByRole('button', { name: '關閉設定面板', exact: true }).click();
  await page.getByRole('button', { name: '切換正向線模式', exact: true }).click();
  if (await forward.first().getAttribute('d') !== original) throw new Error('模式切換改動正向線位置');
  if (!await source.locator('.react-flow__handle-left.target').count() || !await source.locator('.react-flow__handle-right.source').count()) throw new Error('缺少左右正向接點');
  await page.screenshot({ path: 'output/playwright/v115-return.png' });
  if (errors.length) throw new Error(errors.join('\n'));
  return 'PASS: return path supports a right-in/left-out intermediate node and bottom endpoints';
}
