async page => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.emulateMedia({ reducedMotion: 'reduce' }); await page.setViewportSize({ width: 1600, height: 1000 });
  const root = page.locator('.app-shell:visible');
  const importFile = async name => { await root.locator('input[type=file]').setInputFiles(name); await page.getByRole('button', { name: '匯入專案', exact: true }).click(); };
  await importFile('public/example.workflow.aov.json');
  await page.getByRole('button', { name: '新增流程步驟', exact: true }).waitFor();
  await root.locator('.node-card').filter({ hasText: '入庫' }).click();
  if (await page.getByText('輸入契約', { exact: false }).isVisible().catch(() => false)) throw new Error('Workflow 洩漏技術欄位');
  await page.getByRole('textbox', { name: '步驟說明', exact: true }).fill('業務說明獨立修改');
  await page.getByRole('tab', { name: '樣式', exact: true }).click();
  await root.locator('input[type=color]').evaluate(el => { Object.getOwnPropertyDescriptor(HTMLInputElement.prototype, 'value').set.call(el, '#cc3366'); el.dispatchEvent(new Event('input', { bubbles: true })); el.dispatchEvent(new Event('change', { bubbles: true })); });
  await page.getByRole('button', { name: '關閉設定面板', exact: true }).click();
  await page.getByRole('button', { name: '顯示完整畫布', exact: true }).click();
  const wfDownload = page.waitForEvent('download'); await page.getByRole('button', { name: '匯出', exact: true }).click(); await (await wfDownload).saveAs('output/playwright/v11.workflow.aov.json');
  await page.screenshot({ path: 'output/playwright/v11-workflow.png' });
  await page.getByRole('button', { name: 'Dataflow', exact: true }).click();
  await importFile('public/example.dataflow.aov.json');
  await page.waitForFunction(() => document.querySelectorAll('#dataflow-editor .workflow-group').length === 3);
  await page.getByRole('button', { name: '顯示完整畫布', exact: true }).click();
  const group = root.locator('.workflow-group').filter({ has: page.locator('strong', { hasText: '入庫' }) });
  const before = await group.evaluate(el => getComputedStyle(el).getPropertyValue('--node-color'));
  if (before !== '#147d64') throw new Error('Dataflow 被 Workflow 自動覆寫');
  await page.getByRole('button', { name: '同步 Workflow 配色', exact: true }).click();
  const after = await group.evaluate(el => getComputedStyle(el).getPropertyValue('--node-color'));
  if (after !== '#cc3366') throw new Error('明確同步配色失敗');
  const child = root.locator('.node-card').filter({ has: page.locator('strong', { hasText: '入庫資料處理' }) });
  if (await child.evaluate(el => getComputedStyle(el).getPropertyValue('--node-color')) !== '#cc3366') throw new Error('群組色未繼承');
  await child.click();
  await page.getByRole('tab', { name: '樣式', exact: true }).click();
  if (!await root.locator('input[type=color]').isDisabled()) throw new Error('群組內節點可以任意改色');
  await page.getByRole('tab', { name: '定義', exact: true }).click();
  await page.getByRole('textbox', { name: 'API 路徑', exact: true }).fill('/inventory/receive');
  await page.getByRole('button', { name: '關閉設定面板', exact: true }).click();
  await page.getByRole('combobox', { name: '新增節點至', exact: true }).selectOption({ label: '入庫' });
  await page.getByRole('button', { name: '新增一般節點', exact: true }).click();
  await page.getByRole('textbox', { name: '節點名稱', exact: true }).fill('記錄庫存異動');
  await page.getByRole('button', { name: '關閉設定面板', exact: true }).click();
  await page.getByRole('button', { name: '顯示完整畫布', exact: true }).click();
  const dfDownload = page.waitForEvent('download'); await page.getByRole('button', { name: '匯出', exact: true }).click(); await (await dfDownload).saveAs('output/playwright/v11.dataflow.aov.json');
  await page.screenshot({ path: 'output/playwright/v11-dataflow.png' });
  await page.getByRole('button', { name: 'Workflow', exact: true }).click();
  if (await root.locator('.node-card').count() !== 3) throw new Error('Dataflow 編輯改變 Workflow');
  await root.locator('.node-card').filter({ hasText: '入庫' }).click();
  await page.getByRole('button', { name: '刪除選取項目', exact: true }).click(); await page.getByRole('button', { name: '刪除項目', exact: true }).click();
  await page.getByRole('button', { name: 'Dataflow', exact: true }).click();
  await root.getByRole('status').filter({ hasText: '不存在' }).waitFor();
  if (await root.locator('.workflow-group').count() !== 3) throw new Error('跨文件刪除造成 Dataflow 遺失');
  await page.getByRole('button', { name: 'Workflow', exact: true }).click(); await page.getByRole('button', { name: '復原', exact: true }).click();
  if (await root.locator('.node-card').count() !== 3) throw new Error('Workflow 復原失敗');
  await page.getByRole('button', { name: 'Dataflow', exact: true }).click();
  await page.waitForFunction(() => {
    const wf = JSON.parse(localStorage.getItem('aov-studio-workflow-v1.1') || 'null');
    const df = JSON.parse(localStorage.getItem('aov-studio-dataflow-v1.1') || 'null');
    return wf?.graphs?.[0]?.nodes?.length === 3 && df?.graphs?.some(g => g.nodes.some(n => n.name === '記錄庫存異動'));
  });
  await page.reload();
  await page.getByRole('button', { name: 'Dataflow', exact: true }).click();
  if (await root.locator('.workflow-group').count() !== 3) throw new Error('重新載入遺失 Dataflow 群組');
  await root.locator('.node-card').filter({ hasText: '記錄庫存異動' }).waitFor();
  await page.getByRole('button', { name: 'Workflow', exact: true }).click();
  await root.locator('.node-card').filter({ hasText: '入庫' }).click();
  if (await page.getByRole('textbox', { name: '步驟說明', exact: true }).inputValue() !== '業務說明獨立修改') throw new Error('重新載入遺失 Workflow 編輯');
  await page.getByRole('button', { name: '關閉設定面板', exact: true }).click();
  if (errors.length) throw new Error(errors.join('\n'));
  return 'PASS: two independent documents, business UI, grouped overview, explicit colors, inherited styles, external API, export, stale references and separate undo';
}
