async page => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  page.removeAllListeners('dialog');
  page.on('dialog', d => d.accept());
  await page.setViewportSize({ width: 1440, height: 1000 });
  if (await page.getByRole('button', { name: '清除', exact: true }).isEnabled()) { await page.getByRole('button', { name: '清除', exact: true }).click(); await page.getByRole('button', { name: '清除目前畫布', exact: true }).click(); }
  if (await page.getByRole('button', { name: '切換淺色主題', exact: true }).count()) await page.getByRole('button', { name: '切換淺色主題', exact: true }).click();
  await page.getByRole('button', { name: '新增一般節點', exact: true }).click();
  await page.getByRole('textbox', { name: '節點名稱', exact: true }).fill('訂單檢查');
  await page.getByRole('textbox', { name: '功能用途', exact: true }).fill('確認訂單必要欄位與數量');
  await page.getByRole('button', { name: '建立子 AOV →', exact: true }).click();
  await page.getByRole('button', { name: '主流程', exact: true }).waitFor();
  if (await page.locator('.node-card').count() !== 2) throw new Error('子圖應有兩個邊界');
  await page.getByRole('button', { name: '新增一般節點', exact: true }).click();
  await page.getByRole('textbox', { name: '節點名稱', exact: true }).fill('檢查必要欄位');
  await page.getByRole('button', { name: '關閉設定面板', exact: true }).click();
  await page.getByRole('button', { name: '清除', exact: true }).click();
  await page.getByRole('dialog').waitFor();
  if (!(await page.getByRole('dialog').innerText()).includes('3 個節點')) throw new Error('清除數量不符');
  await page.getByRole('button', { name: '取消', exact: true }).click();
  if (await page.locator('.node-card').count() !== 3) throw new Error('取消清除改變資料');
  await page.getByRole('button', { name: '清除', exact: true }).click();
  await page.getByRole('button', { name: '清除目前畫布', exact: true }).click();
  if (await page.locator('.node-card').count() !== 0) throw new Error('清除未完成');
  await page.getByRole('button', { name: '復原', exact: true }).click();
  if (await page.locator('.node-card').count() !== 3) throw new Error('復原子圖失敗');
  await page.getByRole('button', { name: '主流程', exact: true }).click();
  await page.getByRole('button', { name: '切換深色主題', exact: true }).click();
  if (await page.locator('html').getAttribute('data-theme') !== 'dark') throw new Error('深色未套用');
  await page.getByRole('status').filter({ hasText: '已暫存' }).waitFor();
  await page.reload();
  await page.getByRole('button', { name: '切換淺色主題', exact: true }).waitFor();
  if (await page.locator('.node-card').count() !== 1) throw new Error('重新載入未恢復草稿');
  await page.screenshot({ path: 'output/playwright/dark.png' });
  await page.getByRole('button', { name: '切換淺色主題', exact: true }).click();
  await page.locator('input[type=file]').setInputFiles('public/example.aov.json');
  await page.getByRole('button', { name: '匯入專案', exact: true }).click();
  await page.getByRole('button', { name: '顯示完整畫布', exact: true }).click();
  if (await page.locator('.node-card').count() !== 2) throw new Error('範例匯入失敗');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: '匯出', exact: true }).click();
  const download = await downloadPromise;
  await download.saveAs('output/playwright/roundtrip.aov.json');
  await page.screenshot({ path: 'output/playwright/light.png' });
  await page.emulateMedia({ reducedMotion: 'reduce' });
  const duration = await page.locator('.canvas-transition').evaluate(el => getComputedStyle(el).animationName);
  if (duration !== 'none') throw new Error('未尊重減少動態效果');
  await page.setViewportSize({ width: 800, height: 800 });
  await page.screenshot({ path: 'output/playwright/compact.png' });
  await page.setViewportSize({ width: 1440, height: 1000 });
  if (errors.length) throw new Error(errors.join('\n'));
  await page.evaluate(() => document.documentElement.dataset.smokeResult = 'passed');
  return 'PASS: 子圖、清除取消／確認／復原、草稿恢復、主題保存、匯入匯出、減少動畫與窄螢幕';
}
